name: quickparked
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_database: ^10.0.6
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.15
  google_maps_flutter: ^2.2.1
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/quickparked.png"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/quickparked_white.png"
  ios: false