import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:quickparked/themes/quickparked_theme.dart';
import 'package:quickparked/views/home_view.dart';
import 'package:firebase_core/firebase_core.dart';

/** This file is generated by Firebase CLI*/
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const QuickParked());
}

class QuickParked extends StatelessWidget {
  const QuickParked({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) => MaterialApp(
      theme: quickParkedThemeData,
      title: 'QuickParked',
      home: const HomeView());
}
